### ISSUE TITLE
links will not change when hovered on 

### ISSUE THREAD

**Issue by TyannaB** [TyannaB/cards#1]
Hey @thomasjbradley 
The code I am using is the code that was in the instructions and I'm having great difficulty with markbot .

**Comment by thomasjbradley** [comment]
Try putting both card `<li>` tags inside the same `<ul>`

**Comment by thomasjbradley** [comment]
Also, the CSS file isn't connected. The `<link>` tag is in the HTML, but the `href` to `main.css` isn’t filled in completely:
https://github.com/TyannaB/cards/blob/gh-pages/index.html#L7

**Comment by TyannaB** [comment]
When I open the code in the browser it is not showing any changes when I add Informantion or CSS? I do not know why.

**Comment by TyannaB** [comment]
It won't let me open in browser.

**Comment by TyannaB** [comment]
Fixed the problem !
