### ISSUE TITLE
Markbot telling to add code then saying that the suggested added code is incorrect 

### ISSUE THREAD

**Issue by TyannaB** [TyannaB/cards#2]
Hey @thomasjbradley,
Markbot keeps telling me to make my hyperlink to wikipedia like this <a[href="wikipedialinkhere"]>wikipedia</a> then telling me that this is wrong. in the cheatsheets it is not saying anything about squared brackets for links in html either so I am very confused.

**Comment by thomasjbradley** [comment]
Markbot isn't giving you the answer—it's only diagnosing the problem. You're correct that there are no square brackets in the cheat sheets and their shouldn't be. Did you try without the square brackets, exactly how it’s written in the cheat sheets?

p.s. You may notice that what Markbot is showing is a CSS selector, the syntax should be familiar from the “Use all the selectors” assignment where we selected something based on its `rel` attribute.
